# Используйте официальный образ Python
FROM python:3.8

# Установите рабочую директорию в контейнере
WORKDIR /backend

# Копируйте файлы зависимостей
COPY ./backend/main_app/requirements.txt .

# Установите зависимости
RUN pip install --no-cache-dir -r requirements.txt

# Копируйте проект Django
COPY ./backend/main_app .

# Запускаем Django-приложение
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
